apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromecastserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromecastserver
  template:
    metadata:
      labels:
        app: chromecastserver
    spec:
      containers:
      - name: chromecastserver
        image: ahendrix/chromecastserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chromecastserver
spec:
  selector:
    app: chromecastserver
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
